name: Publish release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    name: Publish
    needs: [versions]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Install Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Code Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Validate publishing
        run: bun publish --dry-run && bunx jsr publish --dry-run
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to registries
        run: bun publish && bunx jsr publish
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
